import { useState } from "react";

const sections = ["profile", "account", "voice", "appearance", "preferences"];
const labels = { profile: "Perfil", account: "Conta", voice: "Voz e video", appearance: "Aparencia", preferences: "Preferencias" };

export default function SettingsModal({ theme, onThemeChange, uiSounds, onUiSoundsChange, confirmLeaveRoom, onConfirmLeaveChange, onOpenDevices, profile, onProfileChange, onAvatarChange, onClose }) {
  const [active, setActive] = useState("profile");
  const [draft, setDraft] = useState(profile);
  const set = (key, value) => setDraft((current) => ({ ...current, [key]: value }));
  const save = () => onProfileChange({ ...draft, displayName: draft.displayName.trim().slice(0, 24), nickname: draft.nickname.trim().slice(0, 24), customStatus: draft.customStatus.trim().slice(0, 60) });

  return <div className="modal-backdrop" role="presentation"><section className="settings-modal" role="dialog" aria-modal="true" aria-labelledby="settings-title"><header className="settings-header"><div><p className="section-label">Preferencias</p><h2 id="settings-title">Configuracoes</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Fechar configuracoes">x</button></header><div className="settings-layout"><nav className="settings-nav" aria-label="Secoes de configuracoes">{sections.map((section) => <button type="button" key={section} className={active === section ? "settings-nav-active" : ""} onClick={() => setActive(section)}>{labels[section]}</button>)}</nav><div className="settings-content">
    {active === "profile" && <section className="settings-section"><h3>Perfil</h3><div className="profile-preview">{draft.avatarUrl ? <img src={draft.avatarUrl} alt="" /> : (draft.displayName || draft.nickname || "?").slice(0, 1).toUpperCase()}</div><label className="ghost-button profile-upload">Alterar foto<input type="file" accept="image/png,image/jpeg,image/webp" onChange={onAvatarChange} /></label><label className="field"><span>Nome de exibicao</span><input maxLength={24} value={draft.displayName} onChange={(event) => set("displayName", event.target.value)} /></label><label className="field"><span>Nickname</span><input maxLength={24} value={draft.nickname} onChange={(event) => set("nickname", event.target.value)} /></label><label className="field"><span>Status</span><select value={draft.status} onChange={(event) => set("status", event.target.value)}><option>Online</option><option>Ausente</option><option>Nao perturbe</option><option>Invisivel</option></select></label><label className="field"><span>Status personalizado</span><input maxLength={60} placeholder="Defina um status" value={draft.customStatus} onChange={(event) => set("customStatus", event.target.value)} /></label><button type="button" className="primary-button" onClick={save}>Salvar alteracoes</button></section>}
    {active === "account" && <section className="settings-section"><h3>Conta</h3><div className="settings-readonly"><span>Identidade local</span><strong>Este navegador</strong></div><p>Seu perfil e salvo localmente neste navegador. Nao ha cadastro ou conta online.</p></section>}
    {active === "voice" && <section className="settings-section"><h3>Voz e video</h3><p>Escolha microfone, saida de audio e camera.</p><button type="button" className="ghost-button" onClick={onOpenDevices}>Abrir dispositivos</button><div className="settings-readonly"><span>Qualidade de transmissao</span><strong>720p</strong></div><div className="settings-readonly"><span>FPS</span><strong>30</strong></div></section>}
    {active === "appearance" && <section className="settings-section"><h3>Aparencia</h3><label className="field"><span>Tema</span><select value={theme} onChange={(event) => onThemeChange(event.target.value)}><option value="dark">Escuro</option><option value="light">Claro</option><option value="system">Sistema</option></select></label></section>}
    {active === "preferences" && <section className="settings-section"><h3>Preferencias</h3><label className="settings-toggle"><input type="checkbox" checked={uiSounds} onChange={(event) => onUiSoundsChange(event.target.checked)} /><span>Sons da interface</span></label><label className="settings-toggle"><input type="checkbox" checked={confirmLeaveRoom} onChange={(event) => onConfirmLeaveChange(event.target.checked)} /><span>Confirmar ao sair da sala</span></label></section>}
  </div></div></section></div>;
}
